version: "3"

services:
  endee:
    build: ../
    container_name: endee
    ports:
      - "8080:8080"
    command: ./run.sh

  app:
    build: .
    ports:
      - "8501:8501"
    depends_on:
      - endee
      